<html>
<head></head>
<body>
Dear Sampang Superintendent,
<p>Notifying you that Sampang Daily Production Report {{$ReportDate}} has been generated and completely approved.</p>
<br>
<br>
<br>
<i>
This document generated by System, no signature required.<br>
System generated on {{$datetime}}
</i>
</body>
</html>
