<html>
<head></head>
<body>
Dear Madura Superintendent,
<p>Notifying you that Madura Daily Production Report {{$ReportDate}} has been generated and completely approved.</p>
<br>
<br>
<br>
<i>
This document generated by System, no signature required.<br>
System generated on {{$datetime}}
</i>
</body>
</html>
